//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface JokeResponse {
    error: boolean;
    category: JokeCategory;
    joke: string;
    lang: string;
}

export enum JokeCategory {
    Programming = 0,
    Miscellaneous = 1,
    Dark = 2,
    Pun = 3,
    Spooky = 4,
    Christmas = 5,
}

export interface LoginResponse {
    success: boolean;
    token?: string | undefined;
}